name: uacc
description: "Universal AI Call Companion - Samsung PRISM Hackathon Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  
  # Firebase Services
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  firebase_storage: ^12.3.2
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # Navigation and Routing
  go_router: ^14.6.1
  
  # Permissions and Device Access
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  
  # Audio and Media
  audioplayers: ^6.1.0
  
  # Local Notifications
  flutter_local_notifications: ^17.2.3
  
  # HTTP and Network
  http: ^1.2.2
  dio: ^5.7.0
  connectivity_plus: ^6.0.5
  
  # Storage and Cache
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  
  # Utilities
  intl: ^0.19.0
  crypto: ^3.0.5
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  share_plus: ^10.0.2
  
  # Google Services
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  
  # UI Components
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  
  # Security
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  
  # Calendar Integration
  table_calendar: ^3.1.2
  syncfusion_flutter_calendar: ^27.1.58
  
  # Charts and Analytics
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^27.1.58

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true

  # App Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/fonts/
