// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDXS1jLlzVJblfEGn0mpNpuvfM4t-Kj7o',
    appId: '1:295187812275:web:26b1f23f855fbae57445c6',
    messagingSenderId: '295187812275',
    projectId: 'uacc-uacc',
    authDomain: 'uacc-uacc.firebaseapp.com',
    storageBucket: 'uacc-uacc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6sztjn_569Vrb0NI27IbOay6RuDmsUwI',
    appId: '1:295187812275:android:6133513670ab9f697445c6',
    messagingSenderId: '295187812275',
    projectId: 'uacc-uacc',
    storageBucket: 'uacc-uacc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTuwYCPsA146JkDAH3PB7MzEpRtFYGT1A',
    appId: '1:295187812275:ios:1d63675c89bbdb017445c6',
    messagingSenderId: '295187812275',
    projectId: 'uacc-uacc',
    storageBucket: 'uacc-uacc.firebasestorage.app',
    iosBundleId: 'com.example.uacc',
  );
}
